### ISSUE TITLE
Make SiteMatrix config less wonky

### ISSUE THREAD

**Issue by labster** [miraheze/mw-config#440]
Not sure what an Oromoo is, but we definitely don't have a Wiktionary.  https://meta.miraheze.org/wiki/Special:SiteMatrix

Someone will need to modify $wgSiteMatrixSites to make us a little less matrixxy for the time being.
Hints: https://www.mediawiki.org/wiki/Extension:SiteMatrix  Examples: https://git.wikimedia.org/blob/mediawiki%2Fextensions%2FSiteMatrix/master/extension.json

**Comment by JohnFLewis** [comment]
Done.

And for reference Oromoo is a language with code om. Which is why it exists because we host a wiki with the database name omwiki.

**Comment by labster** [comment]
It doesn't seem to have fixed it.  I'm still seeing Wiktionary.  https://en.wiktionary.org/wiki/nope#Adverb

https://git.wikimedia.org/blob/mediawiki%2Fextensions%2FSiteMatrix/master/extension.json#L40 seems to list these sections.  Maybe we just need to change it.

**Comment by labster** [comment]
Oh, I see why @JohnFLewis didn't fix it -- it's impossible to fix without editing the extension.json file.  Thanks WMF for only writing for yourselves.

**Comment by labster** [comment]
Upstream ticket: https://phabricator.wikimedia.org/T132125

**Comment by NDKilla** [comment]
@labster this is documented on mediawiki.org as being specific to wikimedia wikis. I saw your edit which added more technical information.

Basically we could use this but if we wanted to remove default wikis we'd need to fork the official repo.

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T218.
